#pragma once

#include <string>
#include <unordered_map>

// clang-format off

namespace AimoKeyCodes {
// based on
// https://www.toomanyatoms.com/computer/usb_keyboard_codes.html
// https://gist.github.com/MightyPork/6da26e382a7ad91b5496ee55fdc73db2

// not all of these are necessarily support, the keyboard just sends the code
// whether it will also be interpreted correctly is up to the system driver
	inline std::unordered_map<std::string, uint8_t> USBKeyCodes = {
		{"None",                    0x00, },
		{"ErrorRollOver",           0x01, },
		{"A",                       0x04, },
		{"B",                       0x05, },
		{"C",                       0x06, },
		{"D",                       0x07, },
		{"E",                       0x08, },
		{"F",                       0x09, },
		{"G",                       0x0A, },
		{"H",                       0x0B, },
		{"I",                       0x0C, },
		{"J",                       0x0D, },
		{"K",                       0x0E, },
		{"L",                       0x0F, },
		{"M",                       0x10, },
		{"N",                       0x11, },
		{"O",                       0x12, },
		{"P",                       0x13, },
		{"Q",                       0x14, },
		{"R",                       0x15, },
		{"S",                       0x16, },
		{"T",                       0x17, },
		{"U",                       0x18, },
		{"V",                       0x19, },
		{"W",                       0x1A, },
		{"X",                       0x1B, },
		{"Y",                       0x1C, },
		{"Z",                       0x1D, },
		{"1",                       0x1E, },
		{"2",                       0x1F, },
		{"3",                       0x20, },
		{"4",                       0x21, },
		{"5",                       0x22, },
		{"6",                       0x23, },
		{"7",                       0x24, },
		{"8",                       0x25, },
		{"9",                       0x26, },
		{"0",                       0x27, },
		{"Enter",                   0x28, },
		{"Escape",                  0x29, },
		{"Backspace",               0x2A, },
		{"Tab",                     0x2B, },
		{"Space",                   0x2C, },
		{"-",                       0x2D, },
		{"=",                       0x2E, },
		{"[",                       0x2F, },
		{"]",                       0x30, },
		{"ANSI \\",                 0x31, },
		{"ISO #",                   0x32, },
		{";",                       0x33, },
		{"'",                       0x34, },
		{"`",                       0x35, },
		{",",                       0x36, },
		{".",                       0x37, },
		{"/",                       0x38, },
		{"Caps Lock",               0x39, },
		{"F1",                      0x3A, },
		{"F2",                      0x3B, },
		{"F3",                      0x3C, },
		{"F4",                      0x3D, },
		{"F5",                      0x3E, },
		{"F6",                      0x3F, },
		{"F7",                      0x40, },
		{"F8",                      0x41, },
		{"F9",                      0x42, },
		{"F10",                     0x43, },
		{"F11",                     0x44, },
		{"F12",                     0x45, },
		{"PrintScreen",             0x46, },
		{"Scroll Lock",             0x47, },
		{"Pause",                   0x48, },
		{"Insert",                  0x49, },
		{"Home",                    0x4A, },
		{"PageUp",                  0x4B, },
		{"Delete",                  0x4C, },
		{"End",                     0x4D, },
		{"PageDown",                0x4E, },
		{"Right Arrow",             0x4F, },
		{"Left Arrow",              0x50, },
		{"Down Arrow",              0x51, },
		{"Up Arrow",                0x52, },
		{"Num Lock",                0x53, },
		{"Num /",                   0x54, },
		{"Num *",                   0x55, },
		{"Num -",                   0x56, },
		{"Num +",                   0x57, },
		{"Num Enter",               0x58, },
		{"Num 1",                   0x59, },
		{"Num 2",                   0x5A, },
		{"Num 3",                   0x5B, },
		{"Num 4",                   0x5C, },
		{"Num 5",                   0x5D, },
		{"Num 6",                   0x5E, },
		{"Num 7",                   0x5F, },
		{"Num 8",                   0x60, },
		{"Num 9",                   0x61, },
		{"Num 0",                   0x62, },
		{"Num .",                   0x63, },
		{"ISO \\",                  0x64, },
		{"Application",             0x65, },
		{"Num =",                   0x67, },
		{"F13",                     0x68, },
		{"F14",                     0x69, },
		{"F15",                     0x6A, },
		{"F16",                     0x6B, },
		{"F17",                     0x6C, },
		{"F18",                     0x6D, },
		{"F19",                     0x6E, },
		{"F20",                     0x6F, },
		{"F21",                     0x70, },
		{"F22",                     0x71, },
		{"F23",                     0x72, },
		{"F24",                     0x73, },
		{"Execute",                 0x74, },
		{"Help",                    0x75, },
		{"Menu",                    0x76, },
		{"Select",                  0x77, },
		{"Stop",                    0x78, },
		{"Again",                   0x79, },
		{"Undo",                    0x7A, },
		{"Cut",                     0x7B, },
		{"Copy",                    0x7C, },
		{"Paste",                   0x7D, },
		{"Find",                    0x7E, },
		{"Mute",                    0x7F, },
		{"Volume Up",               0x80, },
		{"Volume Down",             0x81, },
		{"Lock Caps Lock",          0x82, },
		{"Lock Num Lock",           0x83, },
		{"Lock Scroll Lock",        0x84, },
		{"Num ,",                   0x85, },
		{"Num Equal Sign",          0x86, },
		{"International 1",         0x87, },
		{"International 2",         0x88, },
		{"International 3",         0x89, },
		{"International 4",         0x8A, },
		{"International 5",         0x8B, },
		{"International 6",         0x8C, },
		{"International 7",         0x8D, },
		{"International 8",         0x8E, },
		{"International 9",         0x8F, },
		{"LANG1",                   0x90, },
		{"LANG2",                   0x91, },
		{"LANG3",                   0x92, },
		{"LANG4",                   0x93, },
		{"LANG5",                   0x94, },
		{"LANG6",                   0x95, },
		{"LANG7",                   0x96, },
		{"LANG8",                   0x97, },
		{"LANG9",                   0x98, },
		{"Alternate Erase",         0x99, },
		{"SysReq/Attention",        0x9A, },
		{"Cancel",                  0x9B, },
		{"Clear",                   0x9C, },
		{"Prior",                   0x9D, },
		{"Return",                  0x9E, },
		{"Seperator",               0x9F, },
		{"Out",                     0xA0, },
		{"Oper",                    0xA1, },
		{"Clear/Again",             0xA2, },
		{"CrSel/Props",             0xA3, },
		{"ExSel",                   0xA4, },

		{"Num 00",                  0xB0, },
		{"Num 000",                 0xB1, },
		{"Num Thousands Seperator", 0xB2, },
		{"Num Decimal Seperator",   0xB3, },
		{"Num Currency Unit",       0xB4, },
		{"Num Currency Sub-unit",   0xB5, },
		{"Num (",                   0xB6, },
		{"Num )",                   0xB7, },
		{"Num {",                   0xB8, },
		{"Num }",                   0xB9, },
		{"Num Tab",                 0xBA, },
		{"Num Backspace",           0xBB, },
		{"Num A",                   0xBC, },
		{"Num B",                   0xBD, },
		{"Num C",                   0xBE, },
		{"Num D",                   0xBF, },
		{"Num E",                   0xC0, },
		{"Num F",                   0xC1, },
		{"Num XOR",                 0xC2, },
		{"Num ^",                   0xC3, },
		{"Num %",                   0xC4, },
		{"Num <",                   0xC5, },
		{"Num >",                   0xC6, },
		{"Num &",                   0xC7, },
		{"Num &&",                  0xC8, },
		{"Num |",                   0xC9, },
		{"Num ||",                  0xCA, },
		{"Num :",                   0xCB, },
		{"Num #",                   0xCC, },
		{"Num Space",               0xCD, },
		{"Num @",                   0xCE, },
		{"Num !",                   0xCF, },
		{"Num Mem Store",           0xD0, },
		{"Num Mem Recall",          0xD1, },
		{"Num Mem Clear",           0xD2, },
		{"Num Mem Add",             0xD3, },
		{"Num Mem Subtract",        0xD4, },
		{"Num Mem Multiply",        0xD5, },
		{"Num Mem Divide",          0xD6, },
		{"Num +/-",                 0xD7, },
		{"Num Clear",               0xD8, },
		{"Num Clear Entry",         0xD9, },
		{"Num Binary",              0xDA, },
		{"Num Octal",               0xDB, },
		{"Num Decimal",             0xDC, },
		{"Num Hexadecimal",         0xDD, },

		{"LeftControl",             0xE0, },
		{"LeftShift",               0xE1, },
		{"LeftAlt",                 0xE2, },
		{"Left GUI",                0xE3, },
		{"RightControl",            0xE4, },
		{"RightShift",              0xE5, },
		{"RightAlt",                0xE6, },
		{"Right GUI",               0xE7, },
		{"Media Play/Pause",        0xE8, },
		{"Media Stop CD",           0xE9, },
		{"Media Previous",          0xEA, },
		{"Media Next",              0xEB, },
		{"Media Eject",             0xEC, },
		{"Media Volume Up",         0xED, },
		{"Media Volume Down",       0xEE, },
		{"Media Mute",              0xEF, },
		{"Media WWW",               0xF0, },
		{"Media Back",              0xF1, },
		{"Media Forward",           0xF2, },
		{"Media Stop",              0xF3, },
		{"Media Find",              0xF4, },
		{"Media Scroll Up",         0xF5, },
		{"Media Scroll Down",       0xF6, },
		{"Media Edit",              0xF7, },
		{"Media Sleep",             0xF8, },
		{"Media Coffee",            0xF9, },
		{"Media Refresh",           0xFA, },
		{"Media Calc",              0xFB, },
	};
}